spring.application.name=backend

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Recipedrop
spring.datasource.username=recipedrop_user
spring.datasource.password=${RECIPEDROP_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update